controller_frequency: 10
TrajectoryPlannerROS:
  max_vel_x: 0.15
  min_vel_x: -0.15

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

#test kleineren Wert
  acc_lim_x: 0.08
  acc_lim_y: 0.0
  acc_lim_theta: 0.5

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters Werte zum Anpassen
  sim_time: 3.0
  vx_samples: 20
  vtheta_samples: 40
  sim_granularity: 0.5

  

