local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0

  transform_tolerance: 5.0
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
