# Request from Client: RobobrainFaceDetection Node 
bool check_name
string name
---
# Response from Server: FaceDetection Node
bool check_name_resp    # True: directory with name already exists / False: no directory with this name
bool picture_taken

